### PR TITLE
Add terrain topology creation from shapefile

### PR DESCRIPTION
**Pull request by loicgasser**
@gjn we're getting real close ;)

As discussed TerrainTopology class takes an array of GDAL features as argument.

### CODE REVIEW

**Comment by loicgasser** [comment]
@gin I found the error. See: https://github.com/geoadmin/3d-forge/commit/f151c9c39c0b56272f248ee6986d82a0b5d40fc7

We were performing integer divisions and not float divisions.
I also updated the shapefiles and everything makes sense now.

**Comment by gjn** [comment]
Perfect. Thanks alot.

(Of course, our testdata shape files are already quantized coordinates)

**Comment by loicgasser** [comment]
I am adding a method fromTerrainTopology to TerrainTile class that takes a terrainTopology argument.

so code would look like

terrainTile = TerrainTile()
terrainTile.fromTerrainTopology(terrainTopology)
terrainTile.toFile('tileName.terrain')

Makes sense to you as well?

**Comment by gjn** [comment]
Absolutetely.

**Comment by loicgasser** [comment]
Ok so we can now write a .terrain tile from a shapefile. Pretty close from the original file, some small diffrences. :+1: 

For boto copy my config in my .boto file.

**Comment by loicgasser** [comment]
Needs more tests but we're quite close.

**Comment by loicgasser** [comment]
Time to review it sometime tomorrow? Otherwise I ll simply fork this branch and carry on building on top of it as my new unofficial master.

**Comment by loicgasser** [comment]
FYI
The vertices are delta encoded (current value - previous value) first, yielding signed values, and then zig-zag encoded. The documentation fails to mention it.
https://groups.google.com/forum/m/#!topic/cesium-dev/IpcBEvjt-DA
We need some small adaptation in TerrainTile.

**Comment by loicgasser** [comment]
Delta encoding was the missing link. :+1:  I'll let you check it out but I think I fixed all the major issues.

Would be nice to have tests that check the following transformations:

.terrain file -> shapefile -> back in .terrain file
.shapefile -> .terrain file -> back in .shapefile 

Check that we get the same decoded values for everything.

**Comment by gjn** [comment]
Good find. IT alwaysthought those negativen numbers are strange. I'll merge this.

**Pull request merged**
