### PR TITLE
Dev ltclm sql functions

### PR DESCRIPTION
**Pull request by ltclm**
This pr is adding some useful sql functions for 
* db import monitoring (meta.sql)
* data issue debugging (visualize_tms_grid.sql)

### CODE REVIEW

**Comment by gjn** [comment]
Great @ltclm .

Could you write in the README how to use those functions? (postgres dummy here)

**Comment by ltclm** [comment]
done

**Comment by gjn** [comment]
Very nice. Thanks alot for this.

**Comment by loicgasser** [comment]
Super nice!

**Pull request merged**
