### PR TITLE
[WIP] LV03 to WGS1984 grid transformation

### PR DESCRIPTION
**Pull request by procrastinatio**
I think it is better to use `ogr2ogr`to do the datum shift prior to import it, because in python it is cumbersome...
Do not forget to define the `PROJ_LIB`path to use the custom projection settings.

```
export PROJ_LIB=$HOME/3d-forge/proj_date
# using grid
ogr2ogr -s_srs "CH:1903_LV03" -t_srs  "EPSG:4326   wgs84.shp   lv95.shp

#not using grid
ogr2ogr -s_srs "CH:2056" -t_srs  "EPSG:4326   wgs84.shp   lv95.shp
```

### CODE REVIEW

**Comment by gjn** [comment]
I've rebased this branch and will continue to work on it.

**Comment by gjn** [comment]
I'm not specialist, but I wonder why to use `CH:1903_LV03` instead of just `EPSG:21781`

Anyone one knows? @ltclm @loicgasser ?

**Comment by ltclm** [comment]
Using: ``CH:1903_LV03`` instead of ``EPSG:21781`` is enabling the exact transformation with the distortion grid.
https://github.com/geoadmin/3d-forge/pull/86/files#diff-c8a65f83cd62305e449156939866ff38R20
As an alternative we could change the proj4 definition of EPSG:21781 in this file [1], but i would ask @procrastinatio to be sure.

[1] https://github.com/geoadmin/3d-forge/blob/mom_proj/proj_data/epsg

**Comment by gjn** [comment]
We need to know how topo does it. It should be their responsibility to say which transformation to use.

**Comment by ltclm** [comment]
http://www.camptocamp.com/actualite/mapserver-und-gdalogr-mit-proj4-8-0-und-dem-neuen-schweizer-referenzsystem/

**Comment by gjn** [comment]
Thanks alot, @ltclm

**Comment by loicgasser** [comment]
We need to know how topo does it. It should be their responsibility to say which transformation to use.

They use ArcGIS projection module, which is an approximation like proj4j

**Comment by gjn** [comment]
FYI, we had a discussion with Topo and Geodesy. ESRI uses simple transformation -> heights are wrong (was well as 2D). ogr2ogr as used in this PR is good in 2D for CH:1903_LV03, but not for heights, as it doesn't use the geoid for the transformation.

what we acutally need as a full transformation using the geoid. Geodesy will create a command line tool for us (similar to ogr2ogr) that will make this shapefile transformation for us in the correct way. This means we can continue with this PR and integrate it into our process while Geodesy is creating this tool. When Geodesy is delivering the tool, we'll just replace ogr2ogr with the Geodesy tool.

Et Voila, tasks are where they belong: when the respective specialists.

**Comment by ltclm** [comment]
:+1:

**Comment by gjn** [comment]
We will use tool provided by Geodesy to do the transformation. Tooling of this will ultimately be done with puppet, but for now can be done manually by simply copying the program. Emails send.

Therefore, we don't need the definitions in this PR anymore.

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
jenkins test

**Comment by gjn** [comment]
We can close this as we use the Geodesy tool now for the transformation. See https://github.com/geoadmin/3d-forge/pull/107

**Pull request closed without merging**
