### PR TITLE
Add basic stats from bucket

### PR DESCRIPTION
**Pull request by loicgasser**
Here is an example of command:

venv/bin/python forge/scripts/s3_tiles.py -p 2/ count

32 keys have been found for prefix 2/

venv/bin/python forge/scripts/s3_tiles.py -p 2/ list

Listing keys for prefix 2/...
2/0/0.terrain   687     2015-07-13T12:19:59.000Z
2/0/1.terrain   877     2015-07-13T12:19:59.000Z
2/0/2.terrain   861     2015-07-13T12:19:59.000Z
2/0/3.terrain   621     2015-07-13T12:19:59.000Z
2/1/0.terrain   635     2015-07-13T12:19:59.000Z
2/1/1.terrain   864     2015-07-13T12:19:59.000Z
2/1/2.terrain   868     2015-07-13T12:19:59.000Z
2/1/3.terrain   612     2015-07-13T12:19:59.000Z

....

venv/bin/python forge/scripts/s3_tiles.py -p 12/ delete

8190 keys have been deleted

Last command does not work because of S3 bucket policy.
It returns errors: 

Error: 12/4339/3133.terrain(AccessDenied)

@danduk82  Can you give us the ability to deleted files in an S3 bucket please?

One can extend this script to provide an extent etc..

### CODE REVIEW

**Comment by gjn** [comment]
Works well. Of course, it takes quite a while depending on requests.

Are there costs for a) count/list and b) delete?

**Comment by loicgasser** [comment]
$0.005 par tranche de 1 000 demandes
pour Demandes PUT, COPY, POST ou LIST

**Comment by gjn** [comment]
In other words, to be used with care

This includes delete action?

**Comment by loicgasser** [comment]
c'est free delete

**Comment by loicgasser** [comment]
for more info http://aws.amazon.com/fr/s3/pricing/

**Comment by loicgasser** [comment]
@gjn 
ok ready for review, note that we still don't have the right to delete the tiles. I added a few make targets and we are now prompting the user before deleting the tiles.

**Comment by loicgasser** [comment]
delete activated

**Comment by gjn** [comment]
Very usefull, thanks.

**Pull request merged**
