### PR TITLE
Global Geodetic Tiler

### PR DESCRIPTION
**Pull request by loicgasser**
For your information
@danduk82 
Can you please give me back the base URLs for the 3d bucket?

### CODE REVIEW

**Comment by loicgasser** [comment]
@gjn ready for review. This is really not optimized but should be ok for tests.
I'll try to optimize the code and multiprocessing on tile workers.

FYI:
47M     /var/local/cartoweb/tmp/3dpoc/2/c120841_Merge.shp
535M    /var/local/cartoweb/tmp/3dpoc/17/c120841_Merge.shp

**Comment by loicgasser** [comment]
In the corner of a tile in some rare cases we can have up to 5 edges. I need to take that into account. I'll add a fix.

**Comment by loicgasser** [comment]
ok with pentagones as well..

**Comment by loicgasser** [comment]
So it running... You ll see that arbitrary LODs are not the way to go. We re still way too accurate at pretty much all zoom levels (except 17). I ll try to tune it this afternoon using some simple as I already suggested it....

**Comment by loicgasser** [comment]
simple math

**Comment by gjn** [comment]
Are you in office today?

**Comment by loicgasser** [comment]
yes on my way

**Pull request merged**
