### PR TITLE
improve watermark function performance

### PR DESCRIPTION
**Pull request by ltclm**
This pr is increasing the performance of the sql function by approximately 30 % (250ms->170ms).

### CODE REVIEW

**Comment by davidoesch** [comment]
@loicgasser any link or screenshots for the watermark? In general keep it as less intrusive as possible.

**Comment by loicgasser** [comment]
@davidoesch this is not only a sql function lol! Need to add to the project create the tiles etcc..

**Comment by davidoesch** [comment]
Ok then let me know when it is on a Dev project. Imho the terrain  tiles themselves do not need a visible watermark but rather a steganographic approach: the watermark is part of the binary info

**Comment by ltclm** [comment]
sorry @davidoesch there was a typo in the pr name.
This pr is not about watermark it is about watermask,
we dont want to write swisstopo in the 3d tiles, we want to have flat lake surfaces :-)

**Comment by davidoesch** [comment]
Okeee

**Pull request merged**
