### PR TITLE
Better lookup of coords in topology class

### PR DESCRIPTION
**Pull request by loicgasser**
Related to https://github.com/geoadmin/3d-forge/issues/41

With this PR we improve performance by a factor of 3:

2015-07-28 16:44:51,326 | forge.lib.tiler                  | INFO     | It took 0:09:36.732512 create all 180 tiles

without this patch

015-07-28 16:58:09,947 | forge.lib.tiler                  | INFO     | It took 0:03:06.451231 create all 180 tiles

with this patch

### CODE REVIEW

**Comment by gjn** [comment]
Nice one. Simple adaption with huge impact.

**Comment by loicgasser** [comment]
Woo, fast merge.
Yes, I wanted to give it a try for a while, it has indeed a huge impact. :+1:

**Comment by gjn** [comment]
Unless the `str` functions removes some precision from the coordinate, this should be good. Do you think this could be the case?

**Comment by loicgasser** [comment]
up to 11 digits (rounded one) and a combination of 3 coords, that would be surprising. We can always multiply by 10 or 100 if we find out it's a problem.

**Comment by gjn** [comment]
I think it should be good. It's sub mm, no?

**Comment by loicgasser** [comment]
we can also use:

>>> '%.14f' % 1.11111111111991
'1.11111111111991'


if we need more precision

**Comment by loicgasser** [comment]
It's sub mm, no?

What do you mean?

**Comment by gjn** [comment]
11 digits in WGS84 coordinates is better precision than mm in LV95.

**Pull request merged**
