### PR TITLE
Fix Inverted y and z/y/x definition of bgdi tileforge, reduce line length to 90

### PR DESCRIPTION
**Pull request by loicgasser**

### CODE REVIEW

**Comment by gjn** [comment]
Huge update. Didn't have time to have a look yet.

Anyway: terrain service will soon need to be quite stable, as AGI will need it for their building integration. Maybe we push updates to new timestamps for testing purposes?

**Comment by loicgasser** [comment]
Yeah I merged it in my own branch. I'll let you review the other PR.

**Comment by loicgasser** [comment]
> Maybe we push updates to new timestamps for testing purposes?

Yes that would be good. Cédric will give us new data on Monday (8 - 11), we will overwrite the current tiles as terrain is like Swiss Cheese. But after that I agree we should start to play with timestamps.

**Comment by gjn** [comment]
I prefer a cheese that works than no cheese that doesn't work :=) Thursday is very important.

**Pull request merged**
