### PR TITLE
Dev ltclm watermask function

### PR DESCRIPTION
**Pull request by ltclm**

### CODE REVIEW

**Comment by ltclm** [comment]
sql helper function for https://github.com/geoadmin/3d-forge/issues/53

**Comment by loicgasser** [comment]
:+1: Pretty cool. Is it fast?

**Comment by loicgasser** [comment]
small remark, In the case we have no water or only water, don't you think it would be better to only return 0 or 1?
So I would first check if bbox intersects with anything or is within a lake and then rasterize.
What's your take pn that?

**Comment by ltclm** [comment]
It is not that fast, a query takes between 600 and 100 ms, depends on the zoomlevel.
> small remark, In the case we have no water or only water, don't you think it would be better to only return 0 or 1?

Thats exactly what the returned raster of type '1BB' contains. Or do you mean in case a tile lies completely within a lake or outside a lake?

> So I would first check if bbox intersects with anything or is within a lake and then rasterize.
What's your take pn that?

The function makes an intersect with the lake geometry [1] and returns the intersection [2]. the returned raster can be completely within or completely outside a lake geometry.

[1] https://github.com/geoadmin/3d-forge/blob/dev_ltclm_watermask_function/forge/sql/watermask.sql#L41
[2] https://github.com/geoadmin/3d-forge/blob/dev_ltclm_watermask_function/forge/sql/watermask.sql#L39

**Comment by loicgasser** [comment]
yes I mean in the case a tile lies completely within or outside a lake. This check would make it faster right?

**Comment by ltclm** [comment]
The function has been modified.
There is an initial test now which checks if a tile geometry lies compeltely inside or outside a lake.
It the tile is completely outside the lakes, a raster with one pixel with value 0 will be returned.
If the tile is completely inside a lake, a raster with one pixel with value 1 will be returned.

This is increasing the performance as follows:

| performance | old variant | new variant|
| ------------- | ------------- | ------------- |
| tile is partially covered by lakes |250ms  | 250ms|
| tile is completely inside a lake | 300ms  | 50ms|
| tile is completely outside a lake  |200ms  | 50ms|

Since most of our tiles will be completely outside a lake this will have a huge impact on the overall performance.

**Comment by loicgasser** [comment]
Cool! Thanks a lot!

**Pull request merged**
