### PR TITLE
Dev ltclm remote db

### PR DESCRIPTION
**Pull request by ltclm**
this pr is replacing postgres with superuser pgkogis
allows connection to remote database hosts

### CODE REVIEW

**Comment by gjn** [comment]
It doesn't seem to work. When using the remote db, I have an error (seemingly unrelated):

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 376, in _handle_results
    task = get()
TypeError: buffer() takes at least 1 argument (0 given)
```

With localhost, it works as expected. I can connect to remote with tileforge user sucessfully with psql. I don't have time now but will analyse maybe in the afternoon. Maybe you have already an idea, @ltclm or @loicgasser ?

**Comment by ltclm** [comment]
i have just tested the import step with remote db. 
@loicgasser  do you have an idea what could be wrong here?

**Comment by ltclm** [comment]
port and host are initialized here:
https://github.com/geoadmin/3d-forge/blob/e24db2ae94d4cecf60492bc517c480d2941f8a9d/forge/db.py#L78

Dont know where this setting is coming from.

**Comment by ltclm** [comment]
have you changed this line https://github.com/geoadmin/3d-forge/blob/master/database.cfg#L2 ?

**Comment by ltclm** [comment]
I think we have to adapt the code since we have postgis 2.1 now.

**Comment by ltclm** [comment]
we should also pay attention to this know obstacle:
[1] [C2C #190990] Support 3D geoms
http://lists.osgeo.org/pipermail/geos-devel/2013-December/006755.html

**Comment by gjn** [comment]
When I try with single process, I get a different error:

```
2015-07-25 11:04:15,128 | forge.lib.tiler                  | ERROR    | Error while tiles: (psycopg2.ProgrammingError) function _interpolate_height_on_plane(geometry, geometry) does not exist
LINE 1: ...ines_64m.id AS data_break_lines_64m_id, ST_AsEWKB(_interpola...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
 [SQL: 'SELECT data.break_lines_64m.id AS data_break_lines_64m_id, ST_AsEWKB(_interpolate_height_on_plane(data.break_lines_64m.the_geom, ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s))) AS p \nFROM data.break_lines_64m \nWHERE (data.break_lines_64m.the_geom && ST_GeomFromWKB(%(ST_GeomFromWKB_3)s, %(ST_GeomFromWKB_4)s)) AND ST_Intersects(data.break_lines_64m.the_geom, ST_GeomFromWKB(%(ST_GeomFromWKB_3)s, %(ST_GeomFromWKB_4)s)) AND ST_Intersects(data.break_lines_64m.the_geom, ST_GeomFromWKB(%(ST_GeomFromWKB_5)s, %(ST_GeomFromWKB_6)s))'] [parameters: {'ST_GeomFromWKB_5': <read-only buffer for 0x2d607c8, size -1, offset 0 at 0x2d662f0>, 'ST_GeomFromWKB_4': 4326, 'ST_GeomFromWKB_6': 4326, 'ST_GeomFromWKB_1': <read-only buffer for 0x2d5ec00, size -1, offset 0 at 0x2d5b9b0>, 'ST_GeomFromWKB_3': <read-only buffer for 0x2c17cf0, size -1, offset 0 at 0x2d5bf30>, 'ST_GeomFromWKB_2': 4326}]
```
Looks like function is not defined or is not compatible. Maybe we should use same version of postgis on tileforgers and remote servers to get rid of compatibility issues. Otherwise, we can't easily switch our tile generation strategy (switching between remote and localhost), which I think is important.

Regarding size: 71 GB without 0.25. With 0.25, it would be 143GB...And I expect at least 20 times that for the total of Switzerland -> that's almost 3 TB. And if we account for the alps, we might reach 4TB. Ouch.

Also, we might be better off to import to db once...and then sync on file basis between different machines. But to decide that, we need to know the remote performance during tile generation.

**Comment by ltclm** [comment]
our custom function was not installed, i have installed it in the database [1].
moreover i have executed a legacy script which will provide postgis 1.5 behaviour [2].
Could you please re-test.

Impressive numbers, we have no experience with that huge databases...

[1] https://github.com/geoadmin/3d-forge/blob/e24db2ae94d4cecf60492bc517c480d2941f8a9d/forge/sql/_interpolate_height_on_plane.sql
[2] 
```sql
psql -f /usr/share/postgresql/9.4/contrib/postgis-2.1/legacy.sql -d forge
```

**Comment by gjn** [comment]
It's working now.

I'm reprocessing level 17. We'll see about the performance in comparison with localhost db (note: yesterday with localhost, i was developing on same machine and running 1-2 hours levels 10-12 in parallel)

**Comment by ltclm** [comment]
image

**Comment by gjn** [comment]
:=) the db instances is not doing much, so we have some reserve and multiple tileforgers shouldn't impact this by alot.

It seems also faster:
First 8500 tiles with localhost: 21:40
First 8500 tiles with remote: 14:30

**Comment by gjn** [comment]
A third faster. Didn't expect that much. This also means that the clipping on the db is at least a third of the complete tiling process (and probably close to 50%).

**Comment by gjn** [comment]
With localhost: `It took 9:01:33.183543 create all 152803 tiles`

With remote db: `It took 6:15:38.421822 create all 152794 tiles` 

Faster...but 9 tiles less :=) . I wonder why.

**Comment by loicgasser** [comment]
Yup you need to adapt postgis setup to use version 2.1. It is actually simpler.
I can adapt it. (create extension postgis)

**Comment by ltclm** [comment]
data import of 0.25 shape files has been started locally on database instance:
image

**Comment by loicgasser** [comment]
:+1:

**Comment by ltclm** [comment]
zoomlevel 18 / resolution 0.25m has been imported
``2015-07-29 22:52:42,639 | forge.db                         | INFO     | All tables have been created. It took 2:50:23.410531```
The database is now 170 GB, the biggest table has 110 GB and contains 400 Mio features.

```sql
Every 2.0s: df -h | grep lib/postgres; psql -c "select * FROM meta;" -d forge                                                                            Thu Jul 30 07:15:51 2015

/dev/xvdb                                5.0T  167G  4.6T   4% /var/lib/postgresql
         Table         | Size Total | External Size | rowcount
-----------------------+------------+---------------+-----------
 break_lines_0_25m     | 94 GB      | 27 GB         | 396226313
 break_lines_0_5m      | 38 GB      | 11 GB         |         0
 break_lines_1m        | 19 GB      | 5631 MB       |         0
 break_lines_2m        | 10078 MB   | 2968 MB       |         0
 break_lines_4m        | 1967 MB    | 575 MB        |         0
 break_lines_8m        | 904 MB     | 265 MB        |         0
 break_lines_16m       | 653 MB     | 194 MB        |         0
 break_lines_32m       | 458 MB     | 136 MB        |         0
 mnt25_simplified_100m | 390 MB     | 113 MB        |         0
 break_lines_64m       | 330 MB     | 96 MB         |         0
 spatial_ref_sys       | 3360 kB    | 176 kB        |         0
 layer                 | 24 kB      | 24 kB         |         0
 topology              | 24 kB      | 24 kB         |         0
 table_z17_extent      | 16 kB      | 8192 bytes    |         0
(14 rows)

```

**Comment by gjn** [comment]
Creating tiles now. Lots of `Skipping` messages again. Are we sure that shapefiles were/are complete?

**Pull request merged**
