### PR TITLE
Use numpy for topology creation

### PR DESCRIPTION
**Pull request by loicgasser**
This is preliminary work before lighting implementation. I am using numpy as terrain lightning involves a lot of cross products and matrices manipulation.

I think it's simpler which is good. I am testing performance right now.

I also added some tests.

### CODE REVIEW

**Comment by gjn** [comment]
Did you create any tiles with this re-factored code?

**Comment by loicgasser** [comment]
Yes I did all the tiles from 9 to 17 on the new instance.

2015-08-20 07:16:21,888 | forge.lib.tiler                  | INFO     | It took 12:49:57.551558 to create 215014 tiles (52076 were skipped)

What was the last number?
Something like 10 hours?

I should maybe only create numpy lists only at the end. It's handy to have data structured this way for lightning though.

**Comment by gjn** [comment]
I assume created on the new bucket?

**Comment by loicgasser** [comment]
yes new bucket sorry

**Comment by gjn** [comment]
I think Andreas is currently copying from old bucket to new bucket...maybe concurrently as your creation...

**Comment by loicgasser** [comment]
no he stopped I told him yesterday.

**Comment by gjn** [comment]
ping @danduk82 Please copy only levels 0 to 8.

**Comment by loicgasser** [comment]
Don't we have code to do that in this project @gjn ?

**Comment by gjn** [comment]
Only moving within same bucket.

@danduk82 took this code and adapted to copy from bucket to bucket.

**Comment by gjn** [comment]
For such re-factorings, it would be great to have some tests to compare results before/after.

**Comment by loicgasser** [comment]
Agree that's why I used the new bucket to do that.

**Comment by danduk82** [comment]
The copy script will take me a couple of hours more I think, anyway @loicgasser  has re-generated the tiles in the new bucket. It should work.

@loicgasser does the numpy version perform better?

**Comment by loicgasser** [comment]
It does not, because numpy arrays are changing too often at the moment. I'll make a small change and comvert to numpy arrays only at the end.

**Comment by gjn** [comment]
@loicgasser , could you compare a couple of new tiles with the old ones?

The new bucket can't be tested in application yet, so tiles can't be verified this way. `3d.dev.bgdi.ch` returns tiles that can't be processed with Cesium. It tries `https://3d.dev.bgdi.ch/1.0.0/ch.swisstopo.terrain.3d/default/20151231/4326/0/1/0.terrain`, fails to handle it and stops trying to download other tiles.

**Comment by loicgasser** [comment]
I guess that `3d.dev.bgdi.ch` is pointing to the new bucket.
`https://3d.dev.bgdi.ch/1.0.0/ch.swisstopo.terrain.3d/default/20151231/4326/0/1/0.terrain` has a bad header and is not part of the tiles I created.
I use the lookup dictionary again and then compare the tiles to make sure everything is ok.

**Comment by gjn** [comment]
I compared sizes of the same terrain [1] from old and new bucket and the old is 36K, the new 44K. Same for [2] (19K to 29K). But that might be due to other changes.

Maybe you can transform one of our shapefiles with have in this project, once with master, once with this branch and then compare them. This could be put into a unit tests.

[1] 1.0.0/ch.swisstopo.terrain.3d/default/20151231/4326/15/34211/24899.terrain
[2] /1.0.0/ch.swisstopo.terrain.3d/default/20151231/4326/17/136855/99635.terrain

**Comment by danduk82** [comment]
yes DEV is the only address on new bucket for the moment. 
@gjn : when I'll finish the script shall I still copy tiles from 0-8 levels from the old bucket?

**Comment by gjn** [comment]
Yes.

And probably the layer.json file, but @loicgasser should know about that.

**Comment by loicgasser** [comment]
layer.json is already on the new instance.

**Comment by loicgasser** [comment]
I made a couple of changes on this branch and regenerated the tiles.
The switch to the new bucket took place this morning and everything seems to work like before.
Aldo, Tile generation performance is not negatively impacted anymore.

**Pull request merged**
