### PR TITLE
Create Terrain model and put read logic there

### PR DESCRIPTION
**Pull request by gjn**
This is not to merge yet. It's working and discussion place for the qmesh writer.

@loicgasser I did some refactoring of the reader as the basis for the writer.

I will now continue to do the writer and add some tests.

### CODE REVIEW

**Comment by gjn** [comment]
Ok, writer is now there. We are able to write a terrain file, when we have all the values defined.

I'll add capabilities to the TerrainTile class to display real coordinates.

**Comment by loicgasser** [comment]
Nice!

I'll add capabilities to the TerrainTile class to display real coordinates.
Yes I was gona ask.

**Comment by gjn** [comment]
printing the TerrainTile now renders the SwissGrid Coordinates of the vertices as well. Note: you need to define the lower left and upper right corners of the tile (lon/lat in WSG83) when creating the tile or when reading from a terrain file (this info is _not_ in the terrain file itself)

**Comment by gjn** [comment]
This is ready to be reviewed and merged.

**Comment by loicgasser** [comment]
I like it. Good job.

**Pull request merged**
